<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit49fc59fd1735e0aa6997338baf11daf7
{
    public static $files = array (
        '253c157292f75eb38082b5acb06f3f01' => __DIR__ . '/..' . '/nikic/fast-route/src/functions.php',
        'bd9634f2d41831496de0d3dfe4c94881' => __DIR__ . '/..' . '/symfony/polyfill-php56/bootstrap.php',
        '045cd5d476702c3529ef3e1b9f615e70' => __DIR__ . '/..' . '/swlib/http/src/functions.php',
        '3a6b4a1bc7c69c0620b4ef88fb5d27d0' => __DIR__ . '/..' . '/swlib/saber/src/include/functions.php',
        'd0dca54c1bcbed938a539389e43e6364' => __DIR__ . '/../..' . '/App/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Util\\' => 22,
            'Symfony\\Polyfill\\Php56\\' => 23,
            'Swlib\\Util\\' => 11,
            'Swlib\\Saber\\' => 12,
            'Swlib\\Http\\' => 11,
            'SuperClosure\\' => 13,
        ),
        'R' => 
        array (
            'React\\EventLoop\\' => 16,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'PhpParser\\' => 10,
            'PhpAmqpLib\\' => 11,
        ),
        'N' => 
        array (
            'NSQClient\\' => 10,
        ),
        'F' => 
        array (
            'FastRoute\\' => 10,
        ),
        'E' => 
        array (
            'EasySwoole\\Validate\\' => 20,
            'EasySwoole\\Utility\\' => 19,
            'EasySwoole\\Trace\\' => 17,
            'EasySwoole\\Spl\\' => 15,
            'EasySwoole\\Socket\\' => 18,
            'EasySwoole\\Rpc\\' => 15,
            'EasySwoole\\Mysqli\\' => 18,
            'EasySwoole\\Http\\' => 16,
            'EasySwoole\\FastCache\\' => 21,
            'EasySwoole\\EasySwoole\\' => 22,
            'EasySwoole\\Curl\\' => 16,
            'EasySwoole\\Component\\Tests\\' => 27,
            'EasySwoole\\Component\\' => 21,
            'EasySwoole\\Actor\\Test\\' => 22,
            'EasySwoole\\Actor\\' => 17,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Util\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-util',
        ),
        'Symfony\\Polyfill\\Php56\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php56',
        ),
        'Swlib\\Util\\' => 
        array (
            0 => __DIR__ . '/..' . '/swlib/util/src',
        ),
        'Swlib\\Saber\\' => 
        array (
            0 => __DIR__ . '/..' . '/swlib/saber/src',
        ),
        'Swlib\\Http\\' => 
        array (
            0 => __DIR__ . '/..' . '/swlib/http/src',
        ),
        'SuperClosure\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeremeamia/SuperClosure/src',
        ),
        'React\\EventLoop\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/event-loop/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'PhpAmqpLib\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-amqplib/php-amqplib/PhpAmqpLib',
        ),
        'NSQClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/moolex/nsqclient/src',
        ),
        'FastRoute\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/fast-route/src',
        ),
        'EasySwoole\\Validate\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/validate/src',
        ),
        'EasySwoole\\Utility\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/utility/src',
        ),
        'EasySwoole\\Trace\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/trace/src',
        ),
        'EasySwoole\\Spl\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/spl/src',
        ),
        'EasySwoole\\Socket\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/socket/src',
        ),
        'EasySwoole\\Rpc\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/rpc/src',
        ),
        'EasySwoole\\Mysqli\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/mysqli/src',
        ),
        'EasySwoole\\Http\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/http/src',
        ),
        'EasySwoole\\FastCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/fast-cache/src',
        ),
        'EasySwoole\\EasySwoole\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/easyswoole/src',
        ),
        'EasySwoole\\Curl\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/curl/src',
        ),
        'EasySwoole\\Component\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/component/Tests',
        ),
        'EasySwoole\\Component\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/component/src',
        ),
        'EasySwoole\\Actor\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/actor/test',
        ),
        'EasySwoole\\Actor\\' => 
        array (
            0 => __DIR__ . '/..' . '/easyswoole/actor/src',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/dragonmantank/cron-expression/src/Cron',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/App',
        ),
    );

    public static $classMap = array (
        'Swlib\\Saber' => __DIR__ . '/..' . '/swlib/saber/src/Saber.php',
        'Swlib\\SaberGM' => __DIR__ . '/..' . '/swlib/saber/src/SaberGM.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit49fc59fd1735e0aa6997338baf11daf7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit49fc59fd1735e0aa6997338baf11daf7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit49fc59fd1735e0aa6997338baf11daf7::$classMap;

        }, null, ClassLoader::class);
    }
}
